---
#This playbook will provision ec2 instances. It assumes you already have the
#AWS CLI installed, keys configured, Ansible installed, etc.
- name: Provision multiple micro ec2 instances
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Provision instances
    ec2:
       key_name: samy_new #replace with key name
       instance_type: t2.micro #optional: replace with instance type
       region: us-east-1 #optional: replace with region
       image: ami-aa2ea6d0 #replace with AWS image
       group_id: sg-2c7de759 #replace with AWS group ID
       wait: true
       exact_count: 1 #optional: replace with number of instances to spawn
       count_tag:
           Name: node # Replace with name
       instance_tags:
           Name: node # Replace with tag (can be same as name)
    register: ec2

   #This groups the new hosts to allow you to
   #add more tasks further down to run on them
  - name: Add public IP to host group
    add_host: hostname={{ item.public_ip }} groupname=ec2hosts
    with_items: ec2.instances

   #This waits for SSH to come up before running more tasks
  - name: Wait for SSH to come up
    wait_for: hostname={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"

  - include: ec2hosts.yml	
 